import Image from "next/image";
import { supabase } from "@/lib/supabase";

export default async function VerifyPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  const { data } = await supabase
    .from("report_verifications")
    .select("*")
    .eq("verification_id", id)
    .maybeSingle();

  if (!data) {
    return (
      <main className="min-h-screen flex items-center justify-center bg-slate-950 text-white">
        <div className="text-center">
          <div className="flex justify-center mb-4">
            <Image
              src="/patrolsync-logo.png"
              alt="PatrolSync"
              width={60}
              height={60}
            />
          </div>
          <h1 className="text-3xl font-bold">Report not found</h1>
          <p className="text-sm text-slate-400 mt-2">Powered by FenCore Cloud</p>
        </div>
      </main>
    );
  }

  const isCompliance = data.report_type === "Staff Compliance Report";
  const isActivity = data.report_type === "Activity Report";
  const generatedDate = new Date(data.generated_at);

  return (
    <main className="min-h-screen flex items-center justify-center bg-slate-950 text-white">
      <div className="max-w-xl p-10 text-center mx-auto">
        <div className="text-center mb-6">
          <div className="flex justify-center mb-4">
            <Image
              src="/patrolsync-logo.png"
              alt="PatrolSync"
              width={60}
              height={60}
            />
          </div>
          <h1 className="text-3xl font-bold text-green-400">✔ Report Verified</h1>
          <p className="text-sm text-slate-300 mt-2">
            This report was generated by PatrolSync and has not been altered since creation.
          </p>
          <p className="text-sm text-slate-400 mt-2">Powered by FenCore Cloud</p>
        </div>

        <div className="text-left inline-block mt-4 space-y-1">
          <p>
            <strong>Verification ID:</strong> <span className="font-mono">{data.verification_id}</span>
          </p>
          <p><strong>Organisation:</strong> {data.org_name}</p>
          <p><strong>Report type:</strong> {data.report_type}</p>
          <p><strong>Period:</strong> {data.report_from} → {data.report_to}</p>
          <p>
            <strong>Generated:</strong> {generatedDate.toLocaleString("en-GB", {
              year: "numeric",
              month: "2-digit",
              day: "2-digit",
            })} at {generatedDate.toLocaleTimeString("en-GB", {
              hour: "2-digit",
              minute: "2-digit",
            })}
          </p>

          {isActivity ? (
            <>
              <p><strong>Site:</strong> {data.site_name || "—"}</p>
              <p><strong>Total scans:</strong> {data.total_scans ?? data.row_count ?? "—"}</p>
            </>
          ) : null}

          {isCompliance ? (
            <>
              <p><strong>Records:</strong> {data.row_count ?? "—"}</p>
              {data.meta?.summary ? (
                <div className="pt-3 space-y-1">
                  <p><strong>Total guards:</strong> {data.meta.summary.total_guards ?? "—"}</p>
                  <p><strong>Licence records recorded:</strong> {data.meta.summary.licence_records_recorded ?? "—"}</p>
                  <p><strong>Right to work records recorded:</strong> {data.meta.summary.right_to_work_records_recorded ?? "—"}</p>
                  <p><strong>Licence review soon:</strong> {data.meta.summary.licence_review_soon ?? "—"}</p>
                  <p><strong>Right to work review soon:</strong> {data.meta.summary.right_to_work_review_soon ?? "—"}</p>
                </div>
              ) : null}
            </>
          ) : null}
        </div>
      </div>
    </main>
  );
}
