"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";

export default function Home() {
  const [verificationId, setVerificationId] = useState("");
  const router = useRouter();

  function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!verificationId) return;
    router.push(`/verify/${verificationId}`);
  }

  return (
    <main className="min-h-screen flex items-center justify-center bg-slate-950 text-white">
      <div className="w-full max-w-xl p-10">
        <div className="flex flex-col items-center mb-6">
          <Image
            src="/patrolsync-logo.png"
            alt="PatrolSync"
            width={70}
            height={70}
            className="mb-4"
          />

          <h1 className="text-3xl font-bold">
            Verify PatrolSync Report
          </h1>
        </div>

        <p className="text-slate-400 mb-2">
          Enter a PatrolSync Verification ID to confirm that a report
          was generated by the PatrolSync platform.
        </p>

        <p className="text-slate-500 text-sm mb-8">
          Verification records are securely retained for up to 5 years
          from the report generation date.
        </p>

        <form onSubmit={submit} className="flex gap-4">
          <input
            value={verificationId}
            onChange={(e) => setVerificationId(e.target.value)}
            placeholder="PS-XXXXXXX"
            className="flex-1 px-4 py-3 rounded-lg bg-slate-900 border border-slate-700"
          />

          <button
            className="bg-white text-black px-6 py-3 rounded-lg font-semibold"
          >
            Verify
          </button>
        </form>

        <p className="text-xs text-slate-500 mt-4 text-center">
          Powered by FenCore
        </p>
      </div>
    </main>
  );
}