"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";

export default function Home() {
  const [verificationId, setVerificationId] = useState("");
  const router = useRouter();

  function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!verificationId) return;
    router.push(`/verify/${verificationId}`);
  }

  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <div className="mx-auto flex min-h-screen max-w-5xl items-center justify-center px-6 py-10">
        <div className="w-full overflow-hidden rounded-[28px] border border-white/10 bg-gradient-to-b from-slate-900 via-slate-950 to-slate-950 shadow-2xl shadow-black/40">
          <div className="grid gap-0 lg:grid-cols-[1.1fr_.9fr]">
            <section className="border-b border-white/10 px-8 py-10 lg:border-b-0 lg:border-r">
              <div className="flex items-center gap-4">
                <div className="rounded-2xl border border-white/10 bg-white/5 p-3 shadow-lg">
                  <Image
                    src="/patrolsync-logo.png"
                    alt="PatrolSync"
                    width={56}
                    height={56}
                  />
                </div>
                <div>
                  <div className="inline-flex items-center rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-emerald-300">
                    Independent verification
                  </div>
                  <h1 className="mt-3 text-3xl font-bold tracking-tight text-white md:text-4xl">
                    Verify a PatrolSync Report
                  </h1>
                </div>
              </div>

              <p className="mt-6 max-w-2xl text-sm leading-7 text-slate-300">
                Confirm that a PatrolSync report is genuine and matches a stored verification record.
                This page is designed for clients, auditors, insurers, compliance reviewers, and other
                third parties who need independent confirmation that a report was generated by PatrolSync.
              </p>

              <div className="mt-8 grid gap-4 sm:grid-cols-3">
                <div className="rounded-2xl border border-white/8 bg-white/[0.03] p-4">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">
                    Activity reports
                  </p>
                  <p className="mt-2 text-sm text-white">Verify patrol activity records and scan totals.</p>
                </div>
                <div className="rounded-2xl border border-white/8 bg-white/[0.03] p-4">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">
                    Compliance reports
                  </p>
                  <p className="mt-2 text-sm text-white">Confirm staff compliance summaries and report authenticity.</p>
                </div>
                <div className="rounded-2xl border border-white/8 bg-white/[0.03] p-4">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">
                    Trusted evidence
                  </p>
                  <p className="mt-2 text-sm text-white">Supports independent validation without exposing operational data.</p>
                </div>
              </div>
            </section>

            <aside className="px-8 py-10">
              <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6 shadow-lg">
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">
                  Verification lookup
                </p>
                <h2 className="mt-3 text-xl font-semibold text-white">Enter a Verification ID</h2>
                <p className="mt-3 text-sm leading-6 text-slate-300">
                  Use the Verification ID printed on a PatrolSync-generated PDF report.
                </p>

                <form onSubmit={submit} className="mt-6 space-y-4">
                  <div>
                    <label htmlFor="verificationId" className="mb-2 block text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">
                      Verification ID
                    </label>
                    <input
                      id="verificationId"
                      value={verificationId}
                      onChange={(e) => setVerificationId(e.target.value.toUpperCase())}
                      placeholder="PS-COMP-YNQD68CP"
                      className="w-full rounded-2xl border border-slate-700 bg-slate-900 px-4 py-3 text-white outline-none transition focus:border-emerald-400/50 focus:ring-2 focus:ring-emerald-400/20"
                    />
                  </div>

                  <button
                    type="submit"
                    className="w-full rounded-2xl bg-white px-6 py-3 font-semibold text-black transition hover:bg-slate-200"
                  >
                    Verify report
                  </button>
                </form>

                <div className="mt-6 rounded-2xl border border-white/8 bg-slate-900/60 p-4">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">
                    Example formats
                  </p>
                  <div className="mt-3 space-y-2 text-sm text-slate-300">
                    <p><span className="font-mono text-white">PS-COMP-YNQD68CP</span> — Compliance report</p>
                    <p><span className="font-mono text-white">PS-9F55F668</span> — Activity report</p>
                  </div>
                </div>

                <p className="mt-6 text-xs uppercase tracking-[0.2em] text-slate-500">
                  Powered by FenCore Cloud
                </p>
              </div>
            </aside>
          </div>
        </div>
      </div>
    </main>
  );
}